project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!files/"

website:
  title: "Gov 2002"
  favicon: "files/img/gov2002-shield.png"
  navbar:
    pinned: true
    background: "#3498db"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Materials"
        file: materials/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd
      - text: "Ed"
        href: https://edstem.org/us/courses/45093/discussion/
      - text: "Gradescope"
        href: https://www.gradescope.com/courses/589033

  sidebar:
    - title: "Materials"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - materials/index.qmd
        - section: "Course Materials"
          contents:
            - text: "Week 1: Introduction & Probability"
              file: materials/week_01.qmd
            - text: "Week 2: Conditional Probability & Random Variables"
              file: materials/week_02.qmd
            - text: "Week 3: Expectation"
              file: materials/week_03.qmd
            - text: "Week 4: Continuous Random Variables"
              file: materials/week_04.qmd
            - text: "Week 5: Multivariate Distributions"
              file: materials/week_05.qmd
            - text: "Week 6: Conditional Expectation"
              file: materials/week_06.qmd
            - text: "Week 7: Sampling and Estimation"
              file: materials/week_07.qmd
            - text: "Week 8: Asymptotics"
              file: materials/week_08.qmd
            - text: "Week 9: More Asymptotics"
              file: materials/week_09.qmd
            - text: "Week 10: Hypothesis Tests"
              file: materials/week_10.qmd
            - text: "Week 11: Linear Regression"
              file: materials/week_11.qmd
            - text: "Week 12: Algebra of Least Squares"
              file: materials/week_12.qmd
            - text: "Week 13: Statistics of Least Squares"
              file: materials/week_13.qmd
            # - text: "Week 13: Panel and Clustered Data"
            #   file: materials/week_13.qmd
              
    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Resources"
          contents:
            - assignments/index.qmd
            - assignments/problem-sets.qmd
        - section: "Assignments"
          contents:
            - text: "Problem Set 1"
              file: assignments/01_problem_set.qmd
            - text: "Problem Set 2"
              file: assignments/02_problem_set.qmd
            - text: "Problem Set 3"
              file: assignments/03_problem_set.qmd
            - text: "Problem Set 4"
              file: assignments/04_problem_set.qmd
            - text: "Problem Set 5"
              file: assignments/05_problem_set.qmd
            - text: "Problem Set 6"
              file: assignments/06_problem_set.qmd
            - text: "Problem Set 7"
              file: assignments/07_problem_set.qmd
            - text: "Problem Set 8"
              file: assignments/08_problem_set.qmd
            - text: "Problem Set 9"
              file: assignments/09_problem_set.qmd
            - text: "Problem Set 10"
              file: assignments/10_problem_set.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true

execute:
  freeze: auto



