---
title: "Readings, lectures, and videos"
---

 

Each class session has a set of required readings that you should complete ***before*** lecture. 


Here is a list of all the lecture slides the course:

0. [Introduction](/files/slides/00_intro_handout.pdf)
1. [Probability](/files/slides/01_probability_handout.pdf)
2. [Conditional Probability](/files/slides/02_conditional_probability_handout.pdf)
3. [Random Variables](/files/slides/03_variables_handout.pdf)
4. [Expectation](/files/slides/04_expectation_handout.pdf)
5. [Continuous Random Variables](/files/slides/05_continuous_handout.pdf)
6. [Multivariate Distributions](/files/slides/06_multivariate_handout.pdf)
7. [Conditional Expectation](/files/slides/07_cond_exp_handout.pdf)
8. [Sampling and Estimation](/files/slides/08_sampling_handout.pdf)
9. [Asymptotics](/files/slides/09_asymptotics_handout.pdf)
10. [Hypothesis Tests](/files/slides/10_hypothesis_tests_handout.pdf)
11. [Linear Regression](/files/slides/11_linear_model_handout.pdf)
12. [Algebra of Least Squares](/files/slides/12_least_squares_handout.pdf)
13. [Statistics of Least Squares](/files/slides/13_ols_properties_handout.pdf)
<!-- 14. [Panel and Clustered Data](/files/slides/14_clustering_panel_handout.pdf) -->
